version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli

      - docker run -p 8000:8000 -d public.ecr.aws/p7c5q3n4/amazon/dynamodb-local:latest
      - make install



  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - make test


  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - make deploy BUCKET_FOR_LAMBDAS=$BUCKET_FOR_LAMBDAS STAGE=$STAGE INTEGRATION_API_KEY=$INTEGRATION_API_KEY

  post_build:
    commands:

artifacts:
  files:
    - template-export.yaml
    - product-catalog/template-export.yaml